-- MySQL Script generated by MySQL Workbench
-- 03/23/15 17:51:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema example_querysniper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema example_querysniper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `example_querysniper` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `example_querysniper` ;

-- -----------------------------------------------------
-- Table `example_querysniper`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_querysniper`.`companies` ;

CREATE TABLE IF NOT EXISTS `example_querysniper`.`companies` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_querysniper`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_querysniper`.`users` ;

CREATE TABLE IF NOT EXISTS `example_querysniper`.`users` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_users_company_idx` (`company_id` ASC),
  CONSTRAINT `fk_users_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `example_querysniper`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_querysniper`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_querysniper`.`projects` ;

CREATE TABLE IF NOT EXISTS `example_querysniper`.`projects` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `example_querysniper`.`project_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `example_querysniper`.`project_has_users` ;

CREATE TABLE IF NOT EXISTS `example_querysniper`.`project_has_users` (
  `project_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`, `user_id`),
  INDEX `fk_projects_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_projects_has_users_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_projects_has_users_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `example_querysniper`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `example_querysniper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
